module.exports = function(grunt){

    // Files to use rather than try and use grunt.utils
    var files = {
        jshint: ['Gruntfile.js', 'app/**/*.js', 'tests/**/*.js'],
        concatTest: ['tests/**/*.js']
    };

    grunt.initConfig({
        // Allows us to reference values in the package.json file like "name" and "version"
        pkg: grunt.file.readJSON('package.json'),
        jshint: {
            // Add the files to look at
            files: files.jshint

        },
        concat: {
            tests: {
                options: {
                    stripBanners: true,
                    banner: '/**\n * Created by RKGladson and BHesse on <%= grunt.template.today("yyyy-mm-dd") %>\n * Javascript is no excuse to write bad code.™\n * THIS FILE IS AUTOMATICALLY GENERATED FROM FILES IN <rootDir>/tests/\n */\n\n\nvar testData = testData || {};\n'
                },
                src: files.concatTest,
                dest: 'dist/tests/dist.js'
            },
            dist: {
                // the files to concatenate
                src: ['src/**/*.js'],
                // the location of the resulting JS file
                dest: 'dist/<%= pkg.name %>.js'
            }
        },
        watch: {
            files: files.jshint,
            tasks: ['jshint']
        }
    });

    [
        'grunt-contrib-jshint',
        'grunt-contrib-concat',
        'grunt-contrib-watch'
    ].forEach(grunt.loadNpmTasks);
    grunt.registerTask('default', ['jshint']);
};